# Práctica 2 Ingeniería Linguística

In [20]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import load_files
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, mean_absolute_error
from sklearn.model_selection import train_test_split
import re
import nltk
import os
import shutil
import glob


In [64]:
file = open("./Glosarios/glosario_all.txt",encoding='utf-8')
glosario = file.read().split("\n")

In [70]:
glosario_ = []
for x in glosario:
    glosario_.append(x.lower())
    
glosario = glosario_
print(glosario)

['asma', 'defectos', 'medicamentos', 'niños', 'salud', 'personas', 'azúcar', 'caso', 'estudio', 'riesgo', 'medicación', 'embarazo', 'cirujía', 'síntomas', 'dolor', 'mujeres', 'enfermedad', 'problema', 'factores', 'asociación', 'productos', 'artículo', 'artículos', 'ley', 'psoe', 'pp', 'economía', 'reforma', 'mayoría', 'constitución', 'debate', 'española', 'congreso', 'comisión', 'país', 'derecho', 'presidente', 'propuesta', 'rey', 'laboral', 'política', 'gobierno', 'ganar', 'derbi', 'real madrid', 'madrid', 'atlético de madrid', 'barcelona', 'olímpicos', 'final', 'rival', 'balón', 'deportivo', 'penalti', 'liga', 'fútbol', 'equipo', 'aficionados', 'futbolistas', 'torneo', 'temporada', 'minutos', 'gol']


In [71]:
articles = load_files(r"./Documentos/",encoding='utf-8')
X, y = articles.data, articles.target

In [72]:
print(len(y))
print(len(X))
print(y)

90
90
[0 0 1 1 2 1 1 1 2 2 0 0 1 2 0 0 0 1 2 1 0 0 2 1 2 1 2 2 2 0 2 2 0 0 1 1 2
 1 1 0 0 0 1 1 0 2 2 0 1 0 0 1 0 1 0 1 2 1 2 0 1 2 0 2 0 0 1 2 2 2 0 2 2 0
 1 1 1 2 1 0 2 1 0 2 0 2 2 2 1 1]


In [73]:
documents = []
for d in range(0, len(X)):
    document = re.sub(r'\W', ' ', str(X[d]))
    document = document.lower()
    documents.append(document)

In [74]:
vectorizer_ = CountVectorizer(vocabulary = glosario,ngram_range=(1, 2))

print(vectorizer_.vocabulary)

['asma', 'defectos', 'medicamentos', 'niños', 'salud', 'personas', 'azúcar', 'caso', 'estudio', 'riesgo', 'medicación', 'embarazo', 'cirujía', 'síntomas', 'dolor', 'mujeres', 'enfermedad', 'problema', 'factores', 'asociación', 'productos', 'artículo', 'artículos', 'ley', 'psoe', 'pp', 'economía', 'reforma', 'mayoría', 'constitución', 'debate', 'española', 'congreso', 'comisión', 'país', 'derecho', 'presidente', 'propuesta', 'rey', 'laboral', 'política', 'gobierno', 'ganar', 'derbi', 'real madrid', 'madrid', 'atlético de madrid', 'barcelona', 'olímpicos', 'final', 'rival', 'balón', 'deportivo', 'penalti', 'liga', 'fútbol', 'equipo', 'aficionados', 'futbolistas', 'torneo', 'temporada', 'minutos', 'gol']


In [75]:
X_ = vectorizer_.fit_transform(documents).toarray()
print((X_[1]))

[0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 2 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 2 0 0 0 0 4 0 0 0 3 0 0 1 2 3 0 1 0 0 1 4]


In [76]:
#tfidfconverter = TfidfTransformer()
#X_ = tfidfconverter.fit_transform(X_).toarray()
#print(X_[1])

In [77]:
from scipy import spatial

glosario_deportes = np.zeros(X_[0].shape)
glosario_deportes[43:63] = 1
glosario_politica = np.zeros(X_[0].shape)
glosario_politica[22:43] = 1
glosario_salud = np.zeros(X_[0].shape)
glosario_salud[0:21] = 1

result = 1 - spatial.distance.cosine(X_[4], glosario_deportes)
#print(result)

X_deportes = []
X_politica = []
X_salud = []
cosine_distance_deporte = {}
cosine_distance_politica = {}
cosine_distance_salud = {}

for i in range(90):
    if y[i] == 0:
        X_deportes.append(X_[i])
        cosine_distance_deporte[i] = 1 - spatial.distance.cosine(glosario_deportes,X_[i])
        
    elif y[i] == 1:
        X_politica.append(X_[i])
        cosine_distance_politica[i] = 1 - spatial.distance.cosine(glosario_politica,X_[i])
        
    else:
        X_salud.append(X_[i])
        cosine_distance_salud[i] = 1 - spatial.distance.cosine(glosario_salud,X_[i])
    

cosine_distance_deporte  = {k: v for k, v in sorted(cosine_distance_deporte.items(), key=lambda item: item[1])}
cosine_distance_politica = {k: v for k, v in sorted(cosine_distance_politica.items(), key=lambda item: item[1])}
cosine_distance_salud = {k: v for k, v in sorted(cosine_distance_salud.items(), key=lambda item: item[1])}


print(cosine_distance_deporte)
print('####################################################################################################')
print(cosine_distance_politica)
print('####################################################################################################')
print(cosine_distance_salud)
    
  

{65: 0.21081851067789192, 15: 0.22360679774997894, 64: 0.24445060351935233, 52: 0.25, 54: 0.2510395055232011, 82: 0.2724746304565331, 21: 0.27279773578818944, 70: 0.27975144247209416, 16: 0.282842712474619, 32: 0.31008683647302115, 41: 0.31943828249996997, 73: 0.32659863237109044, 62: 0.34156502553198664, 79: 0.3585685828003181, 33: 0.3726779962499649, 49: 0.3795360576382948, 50: 0.4, 14: 0.4050957468334666, 11: 0.4129483209670113, 29: 0.45325006416223335, 0: 0.4751644452187054, 84: 0.4880935300919764, 20: 0.49193495504995366, 44: 0.49303180135043745, 59: 0.49852724275079074, 1: 0.5077963596336064, 39: 0.532948040099012, 47: 0.546303217058937, 40: 0.6028035277130152, 10: 0.6085806194501846}
####################################################################################################
{35: 0.02646280620124819, 38: 0.1346870059402947, 60: 0.16402261043504096, 37: 0.19738550848793068, 78: 0.19738550848793068, 48: 0.21821789023599236, 75: 0.2519763153394847, 7: 0.273009453115974, 5: 

In [78]:
cosine_distance_politica = pd.DataFrame.from_dict(cosine_distance_politica,orient='index')
print(cosine_distance_politica)

           0
35  0.026463
38  0.134687
60  0.164023
37  0.197386
78  0.197386
48  0.218218
75  0.251976
7   0.273009
5   0.339422
66  0.343093
17  0.362477
88  0.363696
57  0.364013
2   0.370479
25  0.377964
23  0.393228
51  0.394771
3   0.423405
34  0.458349
89  0.506674
19  0.509510
76  0.523742
55  0.539886
42  0.558081
81  0.574718
43  0.579141
12  0.600284
6   0.630209
53  0.630209
74  0.646718


In [79]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size=0.5, random_state=0)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

45
45
45
45


In [80]:
print(y_train)
print(y_test)

[1 2 0 1 2 0 1 1 0 0 2 1 1 2 0 0 1 0 2 1 0 0 2 1 2 0 0 2 1 1 2 0 0 2 1 0 2
 0 2 2 2 2 0 0 0]
[1 2 1 0 1 2 2 1 1 1 1 2 0 2 2 0 2 2 2 1 2 1 2 1 2 0 0 0 0 1 0 1 2 2 0 1 1
 0 1 2 0 1 0 1 1]


In [84]:
classifier = LinearSVC()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print('Acuraccy :',accuracy_score(y_test, y_pred))
print('Error:',1-accuracy_score(y_test, y_pred))
#print(classifier.predict_proba(X_test))
#print(classification_report(y_test, y_pred))
matrix = confusion_matrix(y_test, y_pred)
matrix.diagonal()/matrix.sum(axis=1)

Acuraccy : 0.8666666666666667
Error: 0.1333333333333333


array([1.        , 0.94444444, 0.66666667])

In [85]:
classifier = KNeighborsClassifier(5)
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print('Acuraccy :',accuracy_score(y_test, y_pred))
print('Error:',1-accuracy_score(y_test, y_pred))
#print(classifier.predict_proba(X_test))
#print(classification_report(y_test, y_pred))
matrix = confusion_matrix(y_test, y_pred)
matrix.diagonal()/matrix.sum(axis=1)

Acuraccy : 0.8
Error: 0.19999999999999996


array([1.        , 0.72222222, 0.73333333])

In [86]:
classifier = MultinomialNB()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print('Acuraccy :',accuracy_score(y_test, y_pred))
print('Error:',1-accuracy_score(y_test, y_pred))
#print(classifier.predict_proba(X_test))
#print(classification_report(y_test, y_pred))
matrix = confusion_matrix(y_test, y_pred)
matrix.diagonal()/matrix.sum(axis=1)

Acuraccy : 0.8888888888888888
Error: 0.11111111111111116


array([1.        , 1.        , 0.66666667])

# Ordenador por carpetas


In [36]:
#os.rename("path/to/current/file.foo", "path/to/new/destination/for/file.foo")
#shutil.move("path/to/current/file.foo", "path/to/new/destination/for/file.foo")
#os.replace("path/to/current/file.foo", "path/to/new/destination/for/file.foo"

In [47]:
def load_documents(filenames):
    documents = []
    for i in filenames:
        file_document = open(i,'r',encoding='utf-8')
        documents.append(file_document.read().split())
    
    return documents

In [48]:
shutil.rmtree('./Pruebas/deporte')
shutil.rmtree('./Pruebas/politica')
shutil.rmtree('./Pruebas/salud')

filenames_documents = glob.glob('./Pruebas/*')
documentos = load_documents(filenames_documents)


documents = []
for d in range(0, len(documentos)):
    document = re.sub(r'\W', ' ', str(documentos[d]))
    document = document.lower()
    documents.append(document)


vectorizer_ = CountVectorizer(vocabulary = glosario,ngram_range=(1, 2))

X = vectorizer_.fit_transform(documents).toarray()

predictions = classifier.predict(X)

os.mkdir("./Pruebas/deporte/")
os.mkdir("./Pruebas/politica/")
os.mkdir("./Pruebas/salud/")

for prediction,filename in zip(predictions,filenames_documents):    
    if prediction == 0:
        shutil.copyfile("./Pruebas/"+filename[10:], "./Pruebas/deporte/"+filename[10:])
    elif prediction == 1:    
         shutil.copyfile("./Pruebas/"+filename[10:], "./Pruebas/politica/"+filename[10:])
    else:
        shutil.copyfile("./Pruebas/"+filename[10:], "./Pruebas/salud/"+filename[10:])
